export const animalBreeds = [
  // Dog Breeds
  'Labrador Retriever',
  'German Shepherd',
  'Golden Retriever',
  'Bulldog',
  'Poodle',
  'Beagle',
  'Rottweiler',
  'Yorkshire Terrier',
  'Boxer',
  'Dachshund',
  'Siberian Husky',
  'Great Dane',
  'Doberman Pinscher',
  'Shih Tzu',
  'Pug',
  'Chihuahua',
  'Boston Terrier',
  'Akita',
  'Cocker Spaniel',
  'Miniature Schnauzer',
  'Border Collie',
  'Shetland Sheepdog',
  'Australian Shepherd',
  'Bichon Frise',
  'Collie',
  'Pomeranian',
  'Weimaraner',
  'Vizsla',
  'Bloodhound',
  'Dalmatian',
  'Alaskan Malamute',
  'Chow Chow',
  'Samoyed',
  'Irish Setter',
  'Basset Hound',
  'Rhodesian Ridgeback',
  'Scottish Terrier',
  'Whippet',
  'Pekingese',
  'Borzoi',
  'Basenji',
  'Bull Terrier',
  'Chinese Crested',
  'Afghan Hound',
  'Belgian Malinois',
  'Newfoundland',
  'Irish Wolfhound',
  'Cavalier King Charles Spaniel',
  'Old English Sheepdog',
  'Havanese',
  'English Springer Spaniel',
  'Anatolian Shepherd Dog',
  'Bullmastiff',
  'Chinese Shar-Pei',
  'Papillon',
  'Black Russian Terrier',
  'Spinone Italiano',
  'Tibetan Mastiff',
  'Portuguese Water Dog',
  'Saluki',
  'American Staffordshire Terrier',
  'Norwich Terrier',
  'Briard',
  'Wirehaired Pointing Griffon',
  'Bernese Mountain Dog',
  'Greater Swiss Mountain Dog',
  'Plott',
  'Lowchen',
  'Irish Terrier',
  'Kerry Blue Terrier',
  'Leonberger',
  'American Eskimo Dog',
  'Scottish Deerhound',
  'Toy Fox Terrier',
  'Norwegian Elkhound',
  'Australian Terrier',
  'Neapolitan Mastiff',
  'English Foxhound',
  'Xoloitzcuintli',
  'Redbone Coonhound',
  'American Water Spaniel',
  'Japanese Chin',
  'Keeshond',
  'Norfolk Terrier',
  'Bedlington Terrier',
  'Manchester Terrier',
  'English Toy Terrier',
  'Sussex Spaniel',
  'Harrier',
  'Otterhound',
  'Ibizan Hound',
  'Coton de Tulear',
  'Field Spaniel',
  'Norbottenspets',
  'Pharaoh Hound',
  'Cirneco dell\'Etna',
  'Finnish Lapphund',
  'American Hairless Terrier',
  'Lagotto Romagnolo',
  'Kai Ken',
  'Cesky Terrier',
  'Dandie Dinmont Terrier',
  'Skye Terrier',
  'Glen of Imaal Terrier',
  'Alaskan Klee Kai',
  'Lancashire Heeler',
  'Miniature Bull Terrier',
  'Bergamasco',
  'Finnish Spitz',
  'Affenpinscher',
  'Drever',
  'Sealyham Terrier',
  'Curly-Coated Retriever',
  'Japanese Chin',
  'Toy Terrier',
  'Kooikerhondje',
  'Finnish Hound',
  'Grand Basset Griffon Vendéen',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Terrier',
  'Austrian Pinscher',
  'Azawakh',
  'Barbet',
  'Basenji',
  'Basset Hound',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Laekenois',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bergamasco',
  'Berger Picard',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Biewer Terrier',
  'Black and Tan Coonhound',
  'Black Russian Terrier',
  'Bloodhound',
  'Bluetick Coonhound',
  'Boerboel',
  'Bohemian Shepherd',
  'Bolognese',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Briard',
  'Brittany',
  'Broholmer',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Cairn Terrier',
  'Canaan Dog',
  'Canadian Eskimo Dog',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Catahoula Leopard Dog',
  'Caucasian Shepherd Dog',
  'Cavalier King Charles Spaniel',
  'Central Asian Shepherd Dog',
  'Cesky Terrier',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chinook',
  'Chow Chow',
  'Clumber Spaniel',
  'Cockapoo',
  'Cocker Spaniel',
  'Collie',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  'Dachshund',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Danish-Swedish Farmdog',
  'Deutscher Wachtelhund',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Drentsche Patrijshond',
  'Drever',
  'Dunker',
  'Dutch Shepherd',
  'English Cocker Spaniel',
  'English Foxhound',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Terrier',
  'Entlebucher Mountain Dog',
  'Estrela Mountain Dog',
  'Eurasier',
  'Field Spaniel',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'French Bulldog',
  'French Spaniel',
  'German Longhaired Pointer',
  'German Pinscher',
  'German Shepherd',
  'German Shorthaired Pointer',
  'German Spitz',
  'German Wirehaired Pointer',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Golden Retriever',
  'Gordon Setter',
  'Grand Basset Griffon Vendéen',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greyhound',
  'Hamiltonstovare',
  'Hanoverian Scenthound',
  'Harrier',
  'Havanese',
  'Hovawart',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Jack Russell Terrier',
  'Japanese Chin',
  'Japanese Spitz',
  'Japanese Terrier',
  'Kai Ken',
  'Karelian Bear Dog',
  'Keeshond',
  'Kerry Blue Terrier',
  'Kishu Ken',
  'Komondor',
  'Kooikerhondje',
  'Kromfohrlander',
  'Kuvasz',
  'Labrador Retriever',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Lapponian Herder',
  'Leonberger',
  'Lhasa Apso',
  'Lowchen',
  'Maltese',
  'Manchester Terrier',
  'Mastiff',
  'Miniature American Shepherd',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Mountain Cur',
  'Mudi',
  'Neapolitan Mastiff',
  'Nederlandse Kooikerhondje',
  'Newfoundland',
  'Norfolk Terrier',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Parson Russell Terrier',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Perro de Presa Canario',
  'Peruvian Inca Orchid',
  'Petit Basset Griffon Vendéen',
  'Pharaoh Hound',
  'Plott',
  'Pointer',
  'Polish Lowland Sheepdog',
  'Pomeranian',
  'Poodle',
  'Portuguese Podengo',
  'Portuguese Pointer',
  'Portuguese Water Dog',
  'Pudelpointer',
  'Pug',
  'Puggle',
  'Puli',
  'Pumi',
  'Pyrenean Mastiff',
  'Pyrenean Shepherd',
  'Rafeiro do Alentejo',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Romanian Mioritic Shepherd Dog',
  'Rottweiler',
  'Russian Toy',
  'Russian Tsvetnaya Bolonka',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Schapendoes',
  'Schipperke',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Shikoku',
  'Siberian Husky',
  'Silken Windhound',
  'Sloughi',
  'Slovakian Rough-haired Pointer',
  'Small Munsterlander Pointer',
  'Smooth Fox Terrier',
  'Soft Coated Wheaten Terrier',
  'Spanish Mastiff',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Stabyhoun',
  'Staffordshire Bull Terrier',
  'Standard Schnauzer',
  'Sussex Spaniel',
  'Swedish Lapphund',
  'Swedish Vallhund',
  'Taiwan Dog',
  'Tatra Sheepdog',
  'Teddy Roosevelt Terrier',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tornjak',
  'Tosa Inu',
  'Toy Fox Terrier',
  'Transylvanian Hound',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Vizsla',
  'Weimaraner',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Xoloitzcuintli',
  'Yorkshire Terrier',

  // Cat Breeds
  'Abyssinian',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Balinese',
  'Bengal',
  'Birman',
  'Bombay',
  'British Shorthair',
  'Burmese',
  'Chartreux',
  'Colorpoint Shorthair',
  'Cornish Rex',
  'Devon Rex',
  'Egyptian Mau',
  'European Burmese',
  'Exotic Shorthair',
  'Havana Brown',
  'Himalayan',
  'Japanese Bobtail',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Nebelung',
  'Norwegian Forest Cat',
  'Ocicat',
  'Oriental',
  'Persian',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Savannah',
  'Scottish Fold',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx',
  'Tonkinese',
  'Turkish Angora',
  'Turkish Van',

  // Other Animal Breeds
  'Lion',
  'Tiger',
  'Leopard',
  'Zebra',
  'Giraffe',
  'Elephant',
  'Panda',
  'Kangaroo',
  'Koala',
  'Gorilla',
  'Penguin',
  'Polar Bear',
  'Hippopotamus',
  'Rhinoceros',
  'Cheetah',
  'Dolphin',
  'Whale',
  'Seal',
  'Walrus',
  'Polar Bear',
  'Puma',
  'Raccoon',
  'Squirrel',
  'Koala',
  'Kangaroo',
  'Gazelle',
  'Antelope',
  'Gorilla',
  'Elephant',
  'Rhinoceros',
  'Giraffe',
  'Kangaroo',
  'Koala',
  'Gorilla',
]